### ISSUE TITLE
This package sets all my icons to black

### ISSUE THREAD

**Issue by adrianmc** [selaias/meteor-simpleweather#2]
I use some other icons in my app, namely those from Font Awesome. Unfortunately, it seems that this package sets the colour and size for ALL &#60;i&#62; tags. It would be good if we could have some control over this.

I've added a pull request to take care of this: https://github.com/selaias/meteor-simpleweather/pull/3

**Comment by selaias** [comment]
Thanks for spotting this!

**Comment by xumx** [comment]
please bump the package version number :)

**Comment by selaias** [comment]
should be ok now thnx :)
