### ISSUE TITLE
Package stopped working :(

### ISSUE THREAD

**Issue by orcprogramming** [selaias/meteor-simpleweather#4]
Hi,

First of all, thanks for the packages :)

Secondly, I'm getting the following error (probably related with Meteor 1.2):
"data.query is undefined" in the following snippet:
```
 $.getJSON(                                                                                                       // 39
      encodeURI(weatherUrl),                                                                                         // 40
      function(data) {                                                                                               // 41
        if(data !== null && data.query !== null && data.query.results !== null && data.query.results.channel.description !== 'Yahoo! Weather Error') {```

Probably because the 'json' package in core is now called 'ejson'. I'll give it a try, but anyway I wanted to report the issue. Cheers!

**Comment by orcprogramming** [comment]
I replaced the 'json' package with 'ejson', but it didn't solve the problem. 

Here is what I'm getting from the logs:

```data.error = {
description:"Tenant 'query_yahooapis_com' access to 'Resource [tenantName=query_yahooapis_com, type=TABLE, name=geo.placefinder, locatorType=FILE, url=/home/y/share/manhattan/application/tenantBundles/yql_query_yahooapis_com_manhattan_v2/YQL-INF/restdefs/geo.placefinder.xml, useUrl=false]' is denied.",
diagnostics:null,
lang:"en-US"
}```

**Comment by selaias** [comment]
its a general issue, I'm trying to understand what is going on

https://github.com/monkeecreate/jquery.simpleWeather/issues/174

**Comment by walsh-conor** [comment]
Has there been any further developments towards resolving this issue? 
If not, do you know of any good alternative weather packages for meteor?

**Comment by selaias** [comment]
I didn't follow the issue on simplweather but its closed as returned to normal. I don;t know any other packages, but you can try forecast.io
